platform: 'illumina'

library: 'WES-Nextera-Rapid-Capture'

hg: '~/data_ref/human_g1k_v37.fasta'

cpu_type: 'xeond'

n_sim: '1' 

threads: '1'

n_cpu: '1'

#Mandatory
gatk: '/mnt/avoton/biofisici/opt_local_gatk/source/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar'